version: '3.9'

services:
  activemq:
    image: symptoma/activemq:latest
    container_name: 'activemq'
    ports:
      - 61616:61616
      - 8161:8161
    volumes:
      - ~/Documents/data/activemq/data:/data/activemq
      - ~/Documents/data/activemq/log:/var/log/activemq
  mongo:
    image: mongo:latest
    container_name: "mongo"
    environment:
      MONGO_DATA_DIR: /data/db
      #MONGO_LOG_DIR: /dev/null
      MONGO_INITDB_DATABASE: admin
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    volumes:
      - ./mongodb/data/db:/data/db
    ports:
      - 27017:27017
    command: mongod --logpath=/dev/null # --quiet
  mongo-express:
    image: mongo-express
    depends_on:
      - mongo
    container_name: "mongo-express"
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      #ME_CONFIG_MONGODB_AUTH_DATABASE: admin
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
    ports:
      - 8081:8081
